<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-170720387-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }
        gtag('js', new Date());
        gtag('config', 'UA-170720387-1');

    </script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Web Design Halesowen | Website Design | Web Designer UK</title>

    <meta name="description" content="UK&#039;s No. 1 website design company &amp; best web designers. Stunning &amp; effective web design in Birmingham, Halesowen, Smethwick, Quinton, Dudley, Oldbury">

    <meta name="keywords" content="web design, web designer, web design halesowen, birmingham web design, birmingham web design company,birmingham web design agency">


    <meta name="author" content="Brilliant Web Design">
    <meta name="theme-color" content="#23d5ab" />

    <link rel="stylesheet" href="7.price-section/allcss.css">
    <!-- 0. global styles   
    <link rel="stylesheet" href="0.global-styles/google-fonts.css">
    <link rel="stylesheet" href="0.global-styles/font-awesome-5-9-0.css">
    <link rel="stylesheet" href="0.global-styles/font-awesome-4-7-0.css">
    <link rel="stylesheet" href="0.global-styles/grid.css">
    <link rel="stylesheet" href="0.global-styles/style.css">
    <link rel="stylesheet" href="0.global-styles/scrollbar.css">

    <link rel="stylesheet" href="1.nav/animated-square.css">
    <link rel="stylesheet" href="1.nav/rotating-diamond.css">
    <link rel="stylesheet" href="1.nav/menuanimation.css">
    <link rel="stylesheet" href="1.nav/nav-overlay.css">
    <link rel="stylesheet" href="1.nav/social.css">

    <link rel="stylesheet" href="2.main-header/3d-button.css">

    <link rel="stylesheet" href="3.what-we-offer/flickity.css">
    <link rel="stylesheet" href="3.what-we-offer/slider.css">

    <link rel="stylesheet" href="4.your-local-design-company/your-local-design-company.css">

    <link rel="stylesheet" href="5.portfolio/portfolio.css">
    <link rel="stylesheet" href="5.portfolio/button-outside.css">

    <link rel="stylesheet" href="6.responsive-web-design/responsive-web-design.css">

    <link rel="stylesheet" href="7.price-section/price.css">

    <link rel="stylesheet" href="8.footer/footer.css">
--->




    <link rel="shortcut icon" type="image/x-icon" href="images/icon/diamond2.png">
    <link rel="shortcut icon" href="images/icon/diamond2.png">
    <link rel="apple-touch-icon" href="images/icon/diamond2.png">
    <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
    <script type="application/ld+json">
        {
            "@context": "http://schema.org",
            "@type": "LocalBusiness",
            "name": "Brilliant Web Design",
            "image": "https://brilliantwebdesign.co.uk/images/section2/table-laptop.jpg",
            "telephone": "07794922161",
            "email": "info@brilliantwebdesign.co.uk",
            "address": {
                "@type": "PostalAddress",
                "streetAddress": "10 Springfield",
                "addressLocality": "Halesowen",
                "postalCode": "B62 8JY"
            },
            "openingHoursSpecification": {
                "@type": "OpeningHoursSpecification",
                "dayOfWeek": {
                    "@type": "DayOfWeek",
                    "name": "Mon-Fri"
                }
            },
            "aggregateRating": {
                "@type": "AggregateRating",
                "ratingValue": "5",
                "bestRating": "5",
                "worstRating": "5",
                "ratingCount": "85"
            }
        }

    </script>
</head>


<body>

    <!-- OVERLAY NAVIGATION START nav-overlay.css --->
    <?php include '1.nav/nav.php';?>
    <!-- OVERLAY NAVIGATION END --->

    <!-- MENU ICON ANIMATION START menuanimation.css --->
    <?php include '1.nav/menuanimation.php';?>
    <!-- MENU ICON ANIMATION START --->

    <!-- Header Start --->
    <header id="particles-js" itemscope itemtype="http://schema.org/LocalBusiness">
        <h2 id="brand">
            <!-- rotating-diamond.css --->
            <div class="wrap rotor-x">
                <div class="wrap rotor-y">
                    <div class="wrap rotor-z">
                        <div class="triangle bottom face-1"></div>
                        <div class="triangle bottom face-2"></div>
                        <div class="triangle bottom face-3"></div>
                        <div class="triangle bottom face-4"></div>
                        <div class="triangle bottom face-5"></div>
                        <div class="triangle bottom face-6"></div>
                        <div class="triangle bottom face-7"></div>
                        <div class="triangle bottom face-8"></div>

                        <div class="triangle middle-bottom face-1"></div>
                        <div class="triangle middle-bottom face-2"></div>
                        <div class="triangle middle-bottom face-3"></div>
                        <div class="triangle middle-bottom face-4"></div>
                        <div class="triangle middle-bottom face-5"></div>
                        <div class="triangle middle-bottom face-6"></div>
                        <div class="triangle middle-bottom face-7"></div>
                        <div class="triangle middle-bottom face-8"></div>

                        <div class="triangle middle-top face-1"></div>
                        <div class="triangle middle-top face-2"></div>
                        <div class="triangle middle-top face-3"></div>
                        <div class="triangle middle-top face-4"></div>
                        <div class="triangle middle-top face-5"></div>
                        <div class="triangle middle-top face-6"></div>
                        <div class="triangle middle-top face-7"></div>
                        <div class="triangle middle-top face-8"></div>

                        <div class="triangle up face-1"></div>
                        <div class="triangle up face-2"></div>
                        <div class="triangle up face-3"></div>
                        <div class="triangle up face-4"></div>
                        <div class="triangle up face-5"></div>
                        <div class="triangle up face-6"></div>
                        <div class="triangle up face-7"></div>
                        <div class="triangle up face-8"></div>

                    </div>
                </div>
            </div> <a id="brand-text" href="https://brilliantwebdesign.co.uk/" itemprop="name">Brilliant<span id="brand-small"> Web Design</span></a>
            <span class="effect aeneas">
                <a href="https://www.facebook.com/brilliantwebdesign.co.uk/" class="fb social-icons" title="Join us on Facebook"><i class="fa fa-facebook" aria-hidden="true"></i></a>

                <a href="https://twitter.com/web_brilliant" class="tw social-icons" title="Join us on Twitter"><i class="fa fa-twitter" aria-hidden="true"></i></a>

                <a href="https://g.page/brilliant-web-design-uk?gm" class="g-plus social-icons" title="Join us on Google+"><i class="fa fa-google-plus" aria-hidden="true"></i></a>

                <a href="https://www.instagram.com/brilliant_web_design/" class="insta social-icons" title="Join us on Instagram"><i class="fa fa-instagram" aria-hidden="true"></i></a>

                <a href="#" class="in social-icons" title="Join us on Linked In"><i class="fa fa-linkedin" areffectia-hidden="true"></i></a>
            </span>
        </h2>



        <div id="header-area">
            <h1 itemprop="description">WEB DESIGN halesowen</h1>
            <h2>Experts in Website Design &amp; SEO</h2>
            <h2>Call us on <span itemprop="telephone" content="+447794922161"><a href="tel:07794922161"> 07794922161</a></span></h2>

            <!-- 3d-button.css --->
            <figure>
                <div>
                    <span><a href="#your-local-design-company-section">ABOUT US</a></span>
                    <span><a href="#your-local-design-company-section">ABOUT US</a></span>
                </div>
            </figure>
        </div>

        <picture>
            <source type="image/webp" srcset="images/responsive12.webp">
            <img id="header-image" src="images/responsive12.png" alt="Responsive web design Halesowen">
        </picture>
    </header>
    <!-- Header End --->



    <section id="what-we-offer">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 module"></div>
            <h2 id="what-we-offer-header">What We Offer</h2>
        </div>
        <div class="row">

            <div class="gallery js-flickity module" data-flickity-options='{ "wrapAround": true }'>
                <?php include '3.what-we-offer/gallery-cell.php'; ?>
            </div>
        </div>
    </section>

    <section id="your-local-design-company-section">
        <div class="row container">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-5 module">

                <picture>
                    <source type="image/webp" srcset="images/section2/table-laptop.webp">
                    <img class="lazy responsive" id="local-web-design-image-pc" src="images/section2/table-laptop.jpg" alt="Website design Halesowen" loading="lazy">
                </picture>

                <picture>
                    <source type="image/webp" srcset="images/section2/table-laptop-mobile.webp">
                    <img class="lazy responsive" id="local-web-design-image-mobile" src="images/section2/table-laptop-mobile.jpg" alt="Website design Halesowen" loading="lazy">
                </picture>

            </div>
            <div class=" col-xs-12 col-sm-12 col-md-12 col-lg-7">
                <div id="section2-box">
                    <div class="paragraph">
                        <h3>Your local web design company!</h3>
                        <span id="typer-text" class="txt-type module" data-wait="2500" data-words='[ " Free business email!", "Free SSL Certificate!", "Google analytics!", "SEO optimised!", "Social media API!", "Mobile responsive!","Fast UK hosting!"]'></span>
                        <p class="section2-p">At Brilliant Web Design our passion is to provide innovative, highly functional, visually appealing and feature-rich website designs.</p>
                        <p class="section2-p">We are a website design company specialising in websites using today&apos;s modern technologies to achieve brilliant on page SEO and website speeds less than 0.10s.</p>
                        <p class="section2-p"> We are professional website designers and website developers who take the time to get to know you and your business needs to build you a unique website that will resonate with your clients and drive business growth. </p>
                        <p class="section2-p">
                            We believe that creating memorable experiences are the best way to connect with your consumers. From dynamic web designs to cutting-edge digital marketing strategies, we believe that the custom solutions we create today will transcend the trends of tomorrow. No matter your product or service, you have a story to tell. And, we’re the best to tell it.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <?php include '5.portfolio/portfolio.php'; ?>



    <?php include '6.responsive-web-design/responsive-web-design.php'; ?>



    <?php include '7.price-section/pricing.php'; ?>




    <?php include '8.footer/footer.php'; ?>
    <!-- FOOTER END --->




    <script src="all-js.js"></script>

    <!-- 0. global styles 
    <script src="0.global-styles/font-awesome.js" crossorigin="anonymous"></script> 
    <script src="0.global-styles/jquery.js"></script>  --->

    <!-- 1. nav 
    <script src="1.nav/menuanimation.js"></script>  
    <script src="1.nav/nav-resize-on-scroll.js"></script> --->

    <script src="1.nav/nav.js"></script>


    <!-- Script for Overlay Change Button 
    <script type="text/javascript" src="1.nav/overlay-change-button.js"> </script> -->

    <!-- 2. main header
    <script type="text/javascript" src="2.main-header/particles.min.js"></script> --->
    <script type="text/javascript" src="2.main-header/app.js"></script>

    <!-- 3. what we offer 
    <script src="3.what-we-offer/flickity.js"></script> --->

    <!-- 4. your local design company 
    <script src="4.your-local-design-company/typeWriter.js"></script> --->

    <!-- 5. porfolio 
    <script src="5.portfolio/vanilla-tilt.js"></script> --->

    <!-- 6. responsive web design --->
    <!-- 7. price table --->
    <!-- 8. footer --->



</body>

</html>
